color-hex-case: lower,
color-hex-length: long,
color-named: never,
comment-empty-line-before: always,
comment-whitespace-inside: always,
declaration-block-trailing-semicolon: always,
declaration-colon-space-after: always,
declaration-colon-space-before: never,
declaration-no-important: true,
font-family-name-quotes: always-where-recommended,
font-weight-notation: numeric,
function-url-quotes: always,
indentation: tab,
media-feature-colon-space-after: always
media-feature-colon-space-before: never,
media-feature-name-no-vendor-prefix: true,
media-feature-parentheses-space-inside: never,
media-feature-range-operator-space-after: never,
media-feature-range-operator-space-before: never,
no-duplicate-selectors: true,
number-leading-zero: always,
rule-empty-line-before: always,
selector-attribute-brackets-space-inside: never,
selector-attribute-operator-space-after: never,
selector-attribute-operator-space-before: never,
selector-attribute-quotes: always,
selector-combinator-space-after: always,
selector-no-vendor-prefix: true,
selector-max-universal: false,
selector-pseudo-class-parentheses-space-inside: never,
selector-pseudo-element-colon-notation: single,
string-quotes: single,
